DbWebManagerSeparatedDAL/DbWebManager/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Ext.Net;
using Ext.Net.MVC;
using System.Data;
using DbWebManager.Models;
using DbWebManager.DAL;
using DbWebManager.UI;

namespace DbWebManager.Controllers
{
    public class ManagerController : Controller
    {
        /// <summary>
        /// Try connect or check connection to current server with settings from Session
        /// </summary>
        /// <returns>MsSqlManager or null</returns>
        private IWorkspaceService GetConnectionFromSession()
        {
            MsSqlConnectionModel connectionModel = Session["ConnectionModel"] as MsSqlConnectionModel;

            try
            {
                IWorkspaceService workspaceService = new WorkspaceService(connectionModel);
                workspaceService.TryConnect();
                return workspaceService;
            }
            catch (Exception)
            {
                // если модель неверна
                Session.Clear();
                return null;
            }
        }

        /// <summary>
        /// Show basic user interface
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return RedirectToAction("Index", "Login");
            }

            TabPanel mainTabPanel = X.GetCmp<TabPanel>("MainTabPanel");

            if (Session["ExceptionObject"] == null)
            {
                // ServerInfoPanel
                Panel serverInfoPanel = workspaceService.GetPanel("Folder=serverInfoPanel", "Folder");
                if (serverInfoPanel != null)
                {
                    serverInfoPanel.AddTo(mainTabPanel);
                    mainTabPanel.SetActiveTab(serverInfoPanel.ID);
                }
            }
            else
            {
                Exception exception = (Exception) Session["ExceptionObject"];

                Panel errorPanel = new Panel();
                errorPanel.ID = "ErrorInfoPanel";
                errorPanel.Title = "Error";
                errorPanel.Padding = 5;
                errorPanel.Closable = true;
                errorPanel.Html = exception.Message;

                errorPanel.AddTo(mainTabPanel);
                mainTabPanel.SetActiveTab(errorPanel.ID);

                Session["ExceptionObject"] = null;
            }

            return View();
        }

        /// <summary>
        /// Try delete object from server
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteData()
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return RedirectToAction("Index", "Login"); // View(model);
            }

            string node = Convert.ToString(Session["node"]);
            string nodeType = Convert.ToString(Session["nodeType"]);

            bool result = workspaceService.DeleteData(node, nodeType);

            if (result)
            {
                X.Msg.Notify(new NotificationConfig()
                {
                    Title = "Deleted",
                    Html = "<b>" + nodeType + " has been deleted!",
                    Width = 250,
                    Height = 150
                }).Show();
            }

            return this.Direct();
        }


        public ActionResult ShowData()
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return RedirectToAction("Index", "Login"); // View(model);
            }

            string node = Convert.ToString(Session["node"]);
            string nodeType = Convert.ToString(Session["nodeType"]);

            TabPanel mainTabPanel = X.GetCmp<TabPanel>("MainTabPanel");

            Panel newPanel = workspaceService.GetPanel(node, nodeType);


            if (newPanel != null)
            {
                newPanel.AddTo(mainTabPanel);
                mainTabPanel.SetActiveTab(newPanel.ID);
            }


            return this.Direct();
        }

        /// <summary>
        /// Add new Tab in MainTabPanel depends of Tree node Id
        /// </summary>
        /// <param name="node"></param>
        /// <param name="nodeType"></param>
        /// <returns></returns>
        public ActionResult AddTab(string node = null, string nodeType = null)
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return RedirectToAction("Index", "Login"); // View(model);
            }

            if (node == null || nodeType == null)
            {
                node = Convert.ToString(Session["node"]);
                nodeType = Convert.ToString(Session["nodeType"]);
            }

            TabPanel mainTabPanel = X.GetCmp<TabPanel>("MainTabPanel");

            Panel newPanel = workspaceService.GetPanel(node, nodeType);

            if (newPanel != null)
            {
                newPanel.AddTo(mainTabPanel);
                mainTabPanel.SetActiveTab(newPanel.ID);
            }


            return this.Direct();
        }


        /// <summary>
        /// Get Node Collection of next Node
        /// </summary>
        /// <param name="node"></param>
        /// <returns></returns>
        public StoreResult GetNode(string node)
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return null;
            }

            MsSqlConnectionModel connectionModel = Session["ConnectionModel"] as MsSqlConnectionModel;
            ITreeService dbTree = new TreeService(connectionModel);
            return dbTree.GetNode(node);
        }


        // --------------------------------------------------------------------------------------------------

        /// <summary>
        /// Get data from Table and add to Panel for editing
        /// </summary>
        /// <param name="parameters"></param>
        /// <returns></returns>
        public ActionResult GetDataFromTable(string parameters)
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return null;
            }

            Ext.Net.MVC.PartialViewResult result = workspaceService.GetDataFromTable(parameters);

            this.GetCmp<TabPanel>("MainTabPanel").SetLastTabAsActive();

            return result;
        }

        /// <summary>
        /// Save changes in DataTable to Server
        /// </summary>
        /// <param name="parameters"></param>
        /// <param name="handler"></param>
        /// <returns></returns>
        public ActionResult HandleChanges(string parameters, StoreDataHandler handler)
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return RedirectToAction("Index", "Login"); // View(model);
            }

            ChangedDataTable newValues = Ext.Net.JSON.Deserialize<ChangedDataTable>(handler.JsonData);

            DataSet currentDataSet = ((DataSet) Session[parameters]).Copy();

            try
            {
                workspaceService.SaveDataTableToServer(parameters, currentDataSet, newValues);

                X.Msg.Notify(new NotificationConfig()
                {
                    Icon = Icon.Accept,
                    Title = "Changed",
                    Html = "<b>Values has been changed!</b>",
                    Width = 250,
                    Height = 150,
                    HideDelay = 5000,
                    Closable = true
                }).Show();

                TabPanel mainTabPanel = X.GetCmp<TabPanel>("MainTabPanel");
                Panel newPanel = workspaceService.GetPanel(parameters, "Table");

                if (newPanel != null)
                {
                    newPanel.AddTo(mainTabPanel);
                    mainTabPanel.SetActiveTab(newPanel.ID);
                }
            }
            catch (Exception Ex)
            {
                X.Msg.Notify(new NotificationConfig()
                {
                    Icon = Icon.Error,
                    Title = "Error!",
                    Html = "<b>Error while saving! Please check your data!</b><br/>" + Ex.Message,
                    Width = 300,
                    Height = 300,
                    HideDelay = 10000,
                    Closable = true
                }).Show();
            }

            return this.Direct();
        }


        // --------------------------------------------------------------------------------------------------

        // --------------------------------------------------------------------------------------------------

        public ActionResult RunQuery(string queryTxt = null, string currentIndex = null)
        {
            IWorkspaceService workspaceService = GetConnectionFromSession();
            if (workspaceService == null)
            {
                return RedirectToAction("Index", "Login");
            }

            int index;
            try
            {
                index = Convert.ToInt32(currentIndex);
            }
            catch (Exception Ex)
            {
                throw Ex;
            }

            TextArea queryTextArea = X.GetCmp<TextArea>("QueryTxt" + index);

            if (queryTxt == null)
            {
                queryTxt = queryTextArea.Text;
            }
            Panel newPanel = workspaceService.GetPanelFromQuery(queryTxt, index);

            if (newPanel != null)
            {
                //Добавляем форму в панель вкладок
                newPanel.AddTo(this.GetCmp<TabPanel>("MainTabPanel"));

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/Index.cshtml
@{
    ViewBag.Title = "Database Web Manager";
}

@Html.X().ResourceManager()

@RenderPage("~/Views/Manager/_ViewPort.cshtml")

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/_Center.cshtml
@(
    Html.X().TabPanel()
        .ID("MainTabPanel")
        .Region(Region.Center)
      )

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/_NavigationBar.cshtml
@(Html.X().Panel()
      .Title("Navigation")
      .Region(Region.West)
      .Layout(LayoutType.Accordion)
      .WidthSpec("25%")
      .Split(true)
      .Collapsible(true)
      .Items(
          Html.X().Panel()
              .ID("Databases")
              .Title("Databases")
              .Border(false)
              .Icon(Icon.FolderGo)
              .ItemsFromPage(this, "~/Views/Manager/_TreePanel.cshtml")
              .AutoScroll(true)
          ,
          Html.X().Panel()
              .Title("Settings")
              .Border(false)
              .Icon(Icon.FolderWrench)
              .Items(
                  Html.X().TreePanel()
                      .ID("MenuTreePanelSettings")
                      .Root(
                          Html.X().Node()
                              .NodeID("Folder=serverInfoPanel")
                              .Text("Server&Connection Information")
                              .CustomAttributes(new ConfigItem("nodeType", "Folder"))
                              .Expandable(false)
                      )
                      .DirectEvents(tpde =>
                      {
                          tpde.ItemDblClick.Url = Url.Action("AddTab");
                          tpde.ItemDblClick.ExtraParams.Add(new {node = JRawValue.From("record.data.id")});
                          tpde.ItemDblClick.ExtraParams.Add(new {nodeType = "Folder"});
                      })
              )
      )
      )

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/_North.cshtml
<script>
    var dialogDeleteConfirm = function () {
        if (confirm("Are you sure?")) {
            Ext.net.DirectMethod.request({
                url: '@(Url.Action("DeleteData", "Manager"))'
            });
            reloadDatabaseTree();
        }
        else { return false; }
        return false;
    };

    var reloadDatabaseTree = function () {
        var userTree = Ext.getCmp('MenuTreePanelUserDatabases');
        userTree.getStore().load();
        userTree.getView().refresh();
        var sysTree = Ext.getCmp('MenuTreePanelSystemDatabases');
        sysTree.getStore().load();
        sysTree.getView().refresh();
    };
</script>

@(
 Html.X().Panel()
        .Title("Menu")
        .Header(true)
        .Region(Region.North)
        .Border(true)
        .Collapsible(true)
        .Items(
            Html.X().Toolbar()
                .Layout(LayoutType.Auto)
                .Items(
                    Html.X().Button()
                        .ID("showData")
                        .ToolTip("Show Data")
                        .Icon(Icon.ScriptGo)
                        .DirectEvents(de => { de.Click.Url = Url.Action("ShowData", "Manager"); }),
                    Html.X().Button()
                        .ID("deleteData")
                        .ToolTip("Delete")
                        .Icon(Icon.ScriptDelete)
                        .Listeners(ls => { ls.Click.Fn = "dialogDeleteConfirm"; }),
                    Html.X().ToolbarFill(),
                    Html.X().Button()
                        .Icon(Icon.PageRefresh)
                        .ID("refreshBtn")
                        .ToolTip("Refresh databases tree")
                        .Listeners(ls => { ls.Click.Fn = "reloadDatabaseTree"; }),
                    Html.X().Button()
                        .ID("newQueryBtn")
                        .Icon(Icon.ScriptAdd)
                        .ToolTip("Add new query")
                        .DirectEvents(de => { de.Click.Url = Url.Action("AddQuery", "Manager"); }),
                    Html.X().ToolbarSeparator(),
                    Html.X().Button()
                        .ID("disconnBtn")
                        .Icon(Icon.Connect)
                        .ToolTip("Disconnect from server")
                        .DirectEvents(de => { de.Click.Url = Url.Action("disconnBtn_Click", "Manager"); })
                )
        )
      )

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/_PanelForGrid.cshtml
@using System.Data
@model DbWebManager.Models.DataTableModel

@(
    Html.X().Panel()
        .ID(Model.Parameters.Replace("-", ""))
        .Title(Model.CurrentTable.TableName)
        .Closable(true)
        .AutoScroll(true)
        .BodyPadding(6)
        .Items(
            Html.X().Toolbar()
                .Items(Model.Buttons),
            Html.X().GridPanel()
                .ID(Model.Parameters.Replace("-", "") + "&Component=GridPanel")
                .Store(
                    Html.X().Store()
                        .ID(Model.Parameters.Replace("-", "") + "&Component=Store")
                        .PageSize(20)
                        .Model(Html.X().Model()
                            .IDProperty("ExtNetMvcId")
                            .Fields(Model.Fields)
                        )
                        .DataSource(Model.CurrentTable)
                )
                .ColumnModel(Model.Columns)
                .SortableColumns(true)
                .View(
                    Html.X().GridView()
                        .StripeRows(true)
                )
                .BottomBar(
                    Html.X().PagingToolbar()
                        .HideRefresh(true)
                )
                .TopBar(
                    Html.X().Toolbar()
                        .Items(
                            Html.X().Button()
                                .Text("Add Row")
                                .Icon(Icon.Add)
                                .Handler("this.up('grid').store.insert(0, {});this.up('grid').editingPlugin.startEdit(0, 0);"),
                            Html.X().Button()
                                .ItemID("btnRemove")
                                .Text("Delete Row")
                                .Icon(Icon.Exclamation)
                                .Handler("this.up('grid').deleteSelected();")
                        )
                )
                .SelectionModel(
                    Html.X().CellSelectionModel()
                        .Mode(SelectionMode.Single)
                )
                .Plugins(
                    Html.X().RowEditing()
                )
                .Buttons(
                    Html.X().Button()
                        .Text("Save to Server")
                        .Icon(Icon.Disk)
                        .DirectEvents(de =>
                        {
                            de.Click.Url = Url.Action("HandleChanges");
                            de.Click.ExtraParams.Add(new Parameter
                            {
                                Name = "data",
                                Value = "this.up('grid').store.getChangedData()",
                                Mode = ParameterMode.Raw,
                                Encode = true
                            });
                            de.Click.ExtraParams.Add(new {parameters = Model.Parameters});
                        })
                        .Handler("this.up('grid').store.commit();")
                )
                .WidthSpec("97%")
                .Margin(0)
                .Padding(0)
        )
      )

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/_TreePanel.cshtml
<script>
    var dialogDeleteConfirm = function () {
        if (confirm("Are you sure?")) {
            Ext.net.DirectMethod.request({
                url: '@(Url.Action("DeleteData", "Manager"))'
            });
            reloadDatabaseTree();
        }
        else { return false; }
        return false;
    };

    var reloadDatabaseTree = function () {
        var userTree = Ext.getCmp('MenuTreePanelUserDatabases');
        userTree.getStore().load();
        userTree.getView().refresh();
        var sysTree = Ext.getCmp('MenuTreePanelSystemDatabases');
        sysTree.getStore().load();
        sysTree.getView().refresh();
    };
</script>


@(Html.X().Menu()
      .ID("ContMenu")
      .Listeners(ls => { })
      .SetPosition(0, 0, true)
      .Items(
          Html.X().MenuItem()
              .ID("selectAll")
              .Text("Select All")
              .DirectEvents(de =>
              {
                  de.Click.Action = "AddTab";
              })
              .Icon(Icon.ScriptStart),
          Html.X().MenuItem()
              .Text("Delete")
              .ID("deleteTable")
              .Listeners(ls => { ls.Click.Fn = "dialogDeleteConfirm"; })
              .Icon(Icon.Delete),
          Html.X().MenuItem()
              .Text("Refresh Tree")
              .ID("refresh")
              .Icon(Icon.DatabaseRefresh)
                  .Listeners(ls => { ls.Click.Fn = "reloadDatabaseTree"; })
              )
      )


@(
    Html.X().TreePanel()
        .ID("MenuTreePanelSystemDatabases")
        .Root(
            Html.X().Node().NodeID("Folder=SystemDatabases").Text("System Databases")
                .AttributesObject(new {nodeType = "Folder"})
        )
        .Store(
            Html.X().TreeStore()
                .Proxy(
                    Html.X().AjaxProxy().Url(Url.Action("GetNode"))
                )
        )
        .DirectEvents(tpde =>
        {
            tpde.ItemClick.Url = Url.Action("SelectItem");
            tpde.ItemClick.ExtraParams.Add(new {node = JRawValue.From("record.data.id")});
            tpde.ItemClick.ExtraParams.Add(new {nodeType = JRawValue.From("record.data.nodeType")});

            tpde.ItemDblClick.Url = Url.Action("AddTab");
            tpde.ItemDblClick.ExtraParams.Add(new {node = JRawValue.From("record.data.id")});
            tpde.ItemDblClick.ExtraParams.Add(new {nodeType = JRawValue.From("record.data.nodeType")});
        })
        .ContextMenuID("ContMenu")
      )

@(
    Html.X().TreePanel()
        .ID("MenuTreePanelUserDatabases")
        .Root(
            Html.X().Node().NodeID("Folder=UserDatabases").Text("User Databases")
                .AttributesObject(new {nodeType = "Folder"})
        )
        .Store(
            Html.X().TreeStore()
                .Proxy(
                    Html.X().AjaxProxy().Url(Url.Action("GetNode"))
                )
        )
        .DirectEvents(tpde =>
        {
            tpde.ItemContextMenu.Url = Url.Action("SelectItem");
            tpde.ItemContextMenu.ExtraParams.Add(new {node = JRawValue.From("record.data.id")});
            tpde.ItemContextMenu.ExtraParams.Add(new {nodeType = JRawValue.From("record.data.nodeType")});

            tpde.ItemClick.Url = Url.Action("SelectItem");
            tpde.ItemClick.ExtraParams.Add(new {node = JRawValue.From("record.data.id")});
            tpde.ItemClick.ExtraParams.Add(new {nodeType = JRawValue.From("record.data.nodeType")});

            tpde.ItemDblClick.Url = Url.Action("AddTab");
            tpde.ItemDblClick.ExtraParams.Add(new {node = JRawValue.From("record.data.id")});
            tpde.ItemDblClick.ExtraParams.Add(new {nodeType = JRawValue.From("record.data.nodeType")});
        })
        .ContextMenuID("ContMenu")
      )

DbWebManagerSeparatedDAL/DbWebManager/Views/Manager/_ViewPort.cshtml
@(
    Html.X().Viewport().Layout(LayoutType.Border)
        .ID("MainViewport")
        .WidthSpec("100%")
        .ItemsFromPage(this, "~/Views/Manager/_North.cshtml")
        .ItemsFromPage(this, "~/Views/Manager/_NavigationBar.cshtml")
        .ItemsFromPage(this, "~/Views/Manager/_Center.cshtml")
      )